spec:
  template:
    spec:
      containers:
        -
          resources:
            requests:
              cpu: "1.0"
              memory: 512Mi
            limits:
              cpu: "2.0"
              memory: 1Gi
          env:
          - name: AMQP_SERVICE_HOST
            value: messaging-szrj9fv2tf.amq-online-infra.svc
          - name: AMQP_SERVICE_PORT
            value: 5672
          - name: AMQP_SERVICE_USERNAME
            value: admin
          - name: AMQP_SERVICE_PASSWORD
            value: password
            