apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  name: scenario-1-space
spec:
  type: standard
  plan: scenario-1-100-customers
  authenticationService:
    type: standard
  endpoints:
    - name: messaging
      service: messaging
      expose:
        type: route
        routeTlsTermination: passthrough
        routeServicePort: amqps
      cert:
        provider: selfsigned
    - name: mqtt
      service: mqtt
      expose:
        type: loadbalancer
        loadBalancerPorts:
        - mqtt
        - mqtts
      cert:
        provider: selfsigned
    - name: console
      service: console
      expose:
        type: route
        routeTlsTermination: reencrypt
        routeServicePort: https
      cert:
        provider: openshift
