apiVersion: v1
kind: List
items:
- apiVersion: enmasse.io/v1beta1
  kind: Address
  metadata:
    name: scenario-1-space.input-online
  spec:
    address: input_online
    plan: transactional-input-queue
    type: queue
- apiVersion: enmasse.io/v1beta1
  kind: Address
  metadata:
    name: scenario-1-space.input-batch
  spec:
    address: input_batch
    plan: batch-input-queue
    type: queue
- apiVersion: enmasse.io/v1beta1
  kind: Address
  metadata:
    name: scenario-1-space.alerts
  spec:
    address: alerts
    plan: customer-alert-topic
    type: topic
