apiVersion: v1
kind: List
items:
- apiVersion: user.enmasse.io/v1alpha1
  kind: MessagingUser
  metadata:
    name: scenario-1-space.user13
  spec:
    username: user13
    authentication:
      type: password
      password: cGFzc3dvcmQ=
    authorization:
      - addresses: ["#"]
        operations: ["send", "recv", "view", "manage"]
      - addresses: ["*"]
        operations: ["send", "recv", "view"]
      - addresses: []
        operations: ["manage"]
