apiVersion: v1
kind: List
items:
- apiVersion: admin.enmasse.io/v1beta1
  kind: StandardInfraConfig
  metadata:
    labels:
      app: enmasse
    name: scenario-1
  spec:
    admin:
      resources:
        memory: 256Mi
    broker:
      addressFullPolicy: FAIL
      resources:
        memory: 512Mi
        storage: 1Gi
    router:
      linkCapacity: 250
      minReplicas: 3
      resources:
        memory: 256Mi
    version: 0.26-SNAPSHOT