apiVersion: v1
kind: List
items:
- apiVersion: admin.enmasse.io/v1beta1
  kind: AddressPlan
  metadata:
    labels:
      app: enmasse
    name: transactional-input-queue
  addressType: queue
  displayName: Transactional Input Queue
  displayOrder: 0
  shortDescription: Creates a transactional input queue on a broker.
  longDescription: Creates a transactional input queue on a broker.
  requiredResources:
  - name: broker
    credit: 0.4
  - name: router
    credit: 0.4
- apiVersion: admin.enmasse.io/v1beta1
  kind: AddressPlan
  metadata:
    labels:
      app: enmasse
    name: batch-input-queue
  addressType: queue
  displayName: Batch Input Queue
  displayOrder: 0
  shortDescription: Creates a batch input queue on a broker.
  longDescription: Creates a batch input queue on a broker.
  requiredResources:
  - name: broker
    credit: 0.4
  - name: router
    credit: 0.4
- apiVersion: admin.enmasse.io/v1beta1
  kind: AddressPlan
  metadata:
    labels:
      app: enmasse
    name: customer-result-queue
  addressType: queue
  displayName: Customer Result Queue
  displayOrder: 0
  shortDescription: Creates a customer result queue on a broker.
  longDescription: Creates a customer result queue on a broker.
  requiredResources:
  - name: broker
    credit: 0.01
  - name: router
    credit: 0.01
- apiVersion: admin.enmasse.io/v1beta1
  kind: AddressPlan
  metadata:
    labels:
      app: enmasse
    name: customer-alert-topic
  addressType: topic
  displayName: Customer Alert Topic
  displayOrder: 0
  shortDescription: Creates a customer alert topic on a broker.
  longDescription: Creates a customer alert topic on a broker.
  requiredResources:
  - name: broker
    credit: 0.1
  - name: router
    credit: 0.1
