apiVersion: v1
kind: List
items:
- apiVersion: admin.enmasse.io/v1beta1
  kind: AddressSpacePlan
  metadata:
    annotations:
      enmasse.io/defined-by: scenario-1
    labels:
      app: enmasse
    name: scenario-1-100-customers
  addressPlans:
  - transactional-input-queue
  - batch-input-queue
  - customer-result-queue
  - customer-alert-topic
  addressSpaceType: standard
  displayName: Scenario 1 Address Space Plan - 100 Users
  displayOrder: 0
  shortDescription: Scenario 1 Address Spaces - 100 Users
  longDescription: Scenario 1 Address Spaces - 100 Users with room to grow up to 1000 Users
  resources:
  - name: broker
    max: 11.0
  - name: router
    max: 11.0
- apiVersion: admin.enmasse.io/v1beta1
  kind: AddressSpacePlan
  metadata:
    annotations:
      enmasse.io/defined-by: scenario-1
    labels:
      app: enmasse
    name: scenario-1-1000-customers
  addressPlans:
  - transactional-input-queue
  - batch-input-queue
  - customer-result-queue
  - customer-alert-topic
  addressSpaceType: standard
  displayName: Scenario 1 Address Space Plan - 1000 Users
  displayOrder: 0
  shortDescription: Scenario 1 Address Spaces - 1000 Users
  longDescription: Scenario 1 Address Spaces - 1000 Users with room to grow up to 10000 Users
  resources:
  - name: broker
    max: 101.0
  - name: router
    max: 101.0
